### ISSUE TITLE
Potenza - Piazza Mario Pagano

### ISSUE THREAD

**Issue by aparzi** [aparzi/informaticaTerritoriale#5]

**Comment by ziomike01** [comment]
cambiare titolo in pizza Mario Pagano

**Comment by aparzi** [comment]
Solved #5.

**Comment by ziomike01** [comment]
ha delle foto simili prova a cambiarle altrimenti non fa niente

**Comment by aparzi** [comment]
purtroppo ci sono poco foto e tutte dalle stesse angolazioni

**Comment by ziomike01** [comment]
allora lascia stare
